import React from 'react';

export interface ReceiptData {
  gymName: string;
  gymPhone: string;
  receiptNo: string;
  date: string;
  customerName: string;
  items: { name: string; qty?: number; price: number; amount: number }[];
  total: number;
  paymentMethod: string;
}

export default function ThermalReceipt({ data }: { data: ReceiptData | null }) {
  if (!data) return null;

  return (
    <div id="thermal-receipt" className="hidden print:block absolute top-0 left-0 w-[80mm] p-4 bg-white text-black font-mono text-sm leading-snug z-[99999] break-words">
      <div className="text-center border-b-2 border-black pb-3 mb-3">
        <h2 className="font-bold text-xl uppercase tracking-wider">{data.gymName}</h2>
        <p className="text-sm">Ph: {data.gymPhone}</p>
        <p className="font-bold mt-1 text-base">PAYMENT RECEIPT</p>
      </div>
      
      <div className="mb-4 space-y-1 text-sm">
        <p><span className="font-bold">Receipt No:</span> {data.receiptNo}</p>
        <p><span className="font-bold">Date:</span> {data.date}</p>
        <p><span className="font-bold">Member:</span> {data.customerName}</p>
      </div>
      
      <table className="w-full mb-3 text-sm">
        <thead className="border-y-2 border-black">
          <tr>
            <th className="text-left font-bold py-2">Description</th>
            <th className="text-right font-bold py-2">Amt(Rs)</th>
          </tr>
        </thead>
        <tbody className="border-b-2 border-black">
          {data.items.map((item, i) => (
            <tr key={i}>
              <td className="py-2 pr-2">
                {item.name}
                {item.qty && item.qty > 1 && (
                  <span className="block text-xs text-gray-800 mt-0.5">
                    {item.qty} x {item.price.toLocaleString()}
                  </span>
                )}
              </td>
              <td className="text-right py-2 align-top">{item.amount.toLocaleString()}</td>
            </tr>
          ))}
        </tbody>
      </table>
      
      <div className="flex justify-between font-bold text-lg mb-2">
        <span>TOTAL:</span>
        <span>Rs. {data.total.toLocaleString()}</span>
      </div>
      
      <div className="mb-6 text-sm">
        <p><span className="font-bold">Paid via:</span> {data.paymentMethod}</p>
      </div>
      
      <div className="text-center border-t-2 border-black pt-3 mt-4">
        <p className="font-bold uppercase mb-1">Thank You!</p>
        <p className="text-xs">No Refund / No Exchange</p>
        <p className="text-xs mt-1">Generated by GymSmart ERP</p>
      </div>
    </div>
  );
}
